version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello CircleCI
      - run:
          name: Print the Current Time
          command: date
      - run:
          command: apt-get update
      - run:
          command: apt-get install gnupg
      - run:
          command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      - run:
          command: echo "deb http://download.mono-project.com/repo/debian stable-stretch main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
      - run:
          command: apt-get update
      - run:
          command: apt install mono-devel
      - run:
          name: build
          command: mcs main.cs
      - run:
          name: execute
          command: mono main.exe