version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello CircleCI
      - run:
          name: Print the Current Time
          command: date
      - run: 
          name: install mono
          command: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          command: echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
          command: sudo apt-get update
          command: sudo apt-get install -y mono-complete
          command: sudo apt-get install -y referenceassemblies-pcl
          command: sudo apt-get install -y ca-certificates-mono
          command: sudo apt-get install -y nunit-console
      - run:
          name: build
          command: mcs main.cs
          command: mono main.exe